public enum Names {
    JOHN, EMILY, MICHAEL, JESSICA, DAVID, LAUREN, CHRISTOPHER, SARAH,
    MATTHEW, RACHEL, JAMES, ASHLEY, ANDREW, MEGAN, WILLIAM, REBECCA,
    BENJAMIN, ELIZABETH, ALEXANDER, VICTORIA, DANIEL, OLIVIA, JOSEPH,
    EMMA, NICHOLAS;
}
