select * from employee;
-- CREATE TABLE employee (
--                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                           first_name VARCHAR(255) NOT NULL,
--                           last_name VARCHAR(255) NOT NULL,
--                           department VARCHAR(255) NOT NULL,
--                           salary INT,
--                           hired DATE,
--                           email VARCHAR(255)
-- );

-- INSERT INTO employee (first_name, last_name, department, salary, hired, email)
-- VALUES
--     ('John', 'Doe', 'IT', 60000, '2022-03-15', 'john.doe@example.com'),
--     ('Alice', 'Smith', 'Sales', 45000, '2022-05-20', 'alice.smith@example.com'),
--     ('Bob', 'Johnson', 'Marketing', 55000, '2022-07-10', 'bob.johnson@example.com'),
--     ('Emily', 'Davis', 'HR', 50000, '2022-09-25', 'emily.davis@example.com'),
--     ('David', 'Brown', 'Finance', 70000, '2022-11-05', 'david.brown@example.com');
