#spring:
#  main:
#    banner-mode: off
#
#  datasource:
#    url: ${datasource.url}
#    username: ${datasource.username}
#    password: ${datasource.password}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    open-in-view: false
#    hibernate:
#      ddl-auto: create
#      show_sql: true
#      format_sql: true
#      dialect: org.hibernate.dialect.MySQLDialect













