public enum Brands {
    BMW, BYD, OPEL, JEEP, AUDI, MAZDA, SKODA, TESLA, DACIA, HONDA, VOLVO,
    TOYOTA, HAVAL, DAEWOO, CITROEN, RENAULT, PEUGEOT, NISSAN, CHEVROLET,
    VOLKSWAGEN, INFINITI, MITSUBISHI, HYUNDAI, SUBARU, LEXUS;
}
